### ISSUE TITLE
JS dates not conforming to yup validator

### ISSUE THREAD

**Issue by jhughes982** [gosh-dre/gmsa_genomic_fhir_webapp#27]
- When we instantiate a date in JS e.g. `new Date("2012-03-04")` we get a console warning that the format does not conform to the required format (see screenshot),
- As far as we can tell, this is because `new Date()` produces more date information than is expected by yup,
- We will need to refactor either the validator or the way we instantiate dates to make them conform,
- This is just a development issue for now as we are passing a date as an initial value. In the final production version of the form all values will be empty initially

![Screenshot 2022-07-14 at 15 42 48](https://user-images.githubusercontent.com/70143648/179009640-2d8190ae-4979-4532-a402-9a7c07e281e9.png)

**Comment by stefpiatek** [comment]
Looks like there's a reasonable amount of examples out there with [yup validation with moment ](https://bionicjulia.com/blog/yup-validation-for-date-time-with-momentjs)

We'll also need to ensure that in the bundle we're sending dates as `YYYY-MM-DD` and datetime as `YYYY-MM-DD HH:MM:SS`
